# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python cv_hm2.py -i1 1-in000001.jpg -i2 1-in001148.jpg -m LS -t 35 > output/output_1_tl.txt
            python cv_hm2.py -i1 1-in000001.jpg -i2 1-in001148.jpg -m RO -t 35 > output/output_1_ro.txt
            python cv_hm2.py -i1 1-in000001.jpg -i2 1-in001148.jpg -m GA -t 0.7 > output/output_1_ga.txt
            python cv_hm2.py -i1 2-in000001.jpg -i2 2-in001800.jpg -m LS -t 35 > output/output_2_tl.txt
            python cv_hm2.py -i1 2-in000001.jpg -i2 2-in001800.jpg -m RO -t 35 > output/output_2_ro.txt
            python cv_hm2.py -i1 2-in000001.jpg -i2 2-in001800.jpg -m GA -t 0.7 > output/output_2_ga.txt
            python cv_hm2.py -i1 3-in000001.jpg -i2 3-in000500.jpg -m LS -t 35 > output/output_3_tl.txt
            python cv_hm2.py -i1 3-in000001.jpg -i2 3-in000500.jpg -m RO -t 35 > output/output_3_ro.txt
            python cv_hm2.py -i1 3-in000001.jpg -i2 3-in000500.jpg -m GA -t 0.7 > output/output_3_ga.txt
            mkdir /home/circleci/repo/test-reports
            mv -f \output/ /home/circleci/repo/test-reports


      - store_artifacts:
          path: test-reports
          destination: test-reports
